services:
    mongodb:
        image: mongo:7.0
        container_name: mongodb
        restart: always
        env_file:
          - .env
        healthcheck:
            test: ["CMD", "mongosh", "--username=${MONGO_INITDB_ROOT_USERNAME}", "--password=${MONGO_INITDB_ROOT_PASSWORD}", "--eval", "db.adminCommand('ping')"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/configdb/mongodb-keyfile"]
        ports:
            - 27017:27017
        extra_hosts:
            - "localhost:0.0.0.0"
        volumes:
            - mongo_db:/data/db
            - ./mongodb-keyfile:/data/configdb/mongodb-keyfile

    backend:
        image: thuannan/aivn-backend:latest
        container_name: backend
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"] 
            interval: 30s          
            timeout: 10s           
            retries: 3         
            start_period: 10s 
        env_file:
            - .env
        environment:
            - INNGEST_DEV=1
            - INNGEST_BASE_URL=http://inngest:8288
        ports:
            - 8000:8000
        depends_on:
            - mongodb
        volumes:
            - ./app/logs/:/src/app/logs/

    inngest:
        image: inngest/inngest:latest
        container_name: inngest
        command: "inngest dev -u http://backend:8000/api/inngest"
        ports:
        - 8288:8288
        depends_on:
            - backend

volumes:
    mongo_db:
